/******************************************************************************/
/****         Generated by IBExpert - Firebird 4.0                         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

CREATE DATABASE 'LOCALHOST/3054:D:\Task\Dados\DADOS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN INTEIRO AS
INTEGER
NOT NULL;

CREATE DOMAIN STRING_40 AS
VARCHAR(40);

CREATE DOMAIN TEXTO AS
BLOB SUB_TYPE 1 SEGMENT SIZE 80;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_TASK START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TASK TO 20;

CREATE GENERATOR GEN_USUARIO START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_USUARIO TO 0;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TASK (
    CODIGO_TASK     INTEIRO,
    USUARIO_TASK    INTEIRO,
    TITULO_TASK     STRING_40,
    DESCRICAO_TASK  TEXTO
);

CREATE TABLE USUARIO (
    CODIGO_USU     INTEIRO NOT NULL,
    DESCRICAO_USU  STRING_40 NOT NULL,
    SENHA_USU      STRING_40
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (CODIGO_USU);